// /** @type {import('prettier').Config} */
// module.exports = {
//     endOfLine: "lf",
//     semi: false,
//     singleQuote: false,
//     tabWidth: 2,
//     trailingComma: "es5",
//     importOrder: [
//         "^(react/(.*)$)|^(react$)",
//         "^(next/(.*)$)|^(next$)",
//         "<THIRD_PARTY_MODULES>",
//         "",
//         "^types$",
//         "^@/types/(.*)$",
//         "^@/config/(.*)$",
//         "^@/summary-row/(.*)$",
//         "^@/hooks/(.*)$",
//         "^@/components/ui/(.*)$",
//         "^@/components/(.*)$",
//         "^@/styles/(.*)$",
//         "^@/app/[lang]/(.*)$",
//         "",
//         "^[./]",
//     ],
//     importOrderSeparation: false,
//     importOrderSortSpecifiers: true,
//     importOrderBuiltinModulesToTop: true,
//     importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
//     importOrderMergeDuplicateImports: true,
//     importOrderCombineTypeAndValueImports: true,
//     plugins: [
//         "prettier-plugin-tailwindcss",
//         require("@ianvs/prettier-plugin-sort-imports"),
//     ],
// }
